name: CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Test
      run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history and tags

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: |
        git fetch --prune --unshallow || true  # Ensure we have full history
        git fetch --tags || true  # Ensure we have all tags
        VERSION=$(git describe --tags --always --dirty)
        CGO_ENABLED=0 go build -v -ldflags "-X main.version=$VERSION" ./cmd/vkftpd

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: vkftpd
        path: vkftpd

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history and tags
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build release binaries
      env:
        CGO_ENABLED: 0
      run: |
        git fetch --prune --unshallow || true  # Ensure we have full history
        git fetch --tags || true  # Ensure we have all tags
        VERSION=$(git describe --tags --always --dirty)
        LDFLAGS="-X main.version=$VERSION"
        GOOS=linux GOARCH=amd64 go build -ldflags "$LDFLAGS" -o vkftpd-linux-amd64 ./cmd/vkftpd
        GOOS=darwin GOARCH=amd64 go build -ldflags "$LDFLAGS" -o vkftpd-darwin-amd64 ./cmd/vkftpd
        GOOS=darwin GOARCH=arm64 go build -ldflags "$LDFLAGS" -o vkftpd-darwin-arm64 ./cmd/vkftpd

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          vkftpd-linux-amd64
          vkftpd-darwin-amd64
          vkftpd-darwin-arm64
        generate_release_notes: true
